/**
 * Types Bridge for SQLite conversion
 * This mimics the Enums that were previously generated by Prisma 
 * so that the application code continues to work without massive refactoring.
 */

export const Role = {
  TRAVELER: "TRAVELER",
  SENDER: "SENDER",
  BOTH: "BOTH",
} as const;

export type Role = (typeof Role)[keyof typeof Role];

export const TripStatus = {
  UPCOMING: "UPCOMING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export type TripStatus = (typeof TripStatus)[keyof typeof TripStatus];

export const PackageStatus = {
  POSTED: "POSTED",
  MATCHED: "MATCHED",
  ACCEPTED: "ACCEPTED",
  PICKED_UP: "PICKED_UP",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
} as const;

export type PackageStatus = (typeof PackageStatus)[keyof typeof PackageStatus];

export const DeliveryStatus = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  PICKED_UP: "PICKED_UP",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
} as const;

export type DeliveryStatus = (typeof DeliveryStatus)[keyof typeof DeliveryStatus];

export const TransactionType = {
  PAYMENT: "PAYMENT",
  PAYOUT: "PAYOUT",
  REFUND: "REFUND",
} as const;

export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType];

export const TransactionStatus = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;

export type TransactionStatus = (typeof TransactionStatus)[keyof typeof TransactionStatus];

export const UrgencyLevel = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  EXPRESS: "EXPRESS",
} as const;

export type UrgencyLevel = (typeof UrgencyLevel)[keyof typeof UrgencyLevel];
